COHERE_API_KEY="1bxiGdTKWg09SX91C9Cl62yzVOGqgyxWfZXBBayA"
[snowflake]
user = "mohammedabsal538"
password = "Mohammed93650@"
account = "hwbodpp-kl66245"
warehouse = "geoboost_warehouse"
database = "GEOBOOST_DATA"
schema = "CULTURE_DATA"